import type { Metadata } from "next";
import "./globals.css";
import Dashboard from "./dashboard/dashboard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Dashboard>{children}</Dashboard>
      </body>
    </html>
  );
}
